In [3]:
import numpy as np
import awkward as ak
import uproot

In [4]:
filename = "ntuples_13723003_0.root"
file = uproot.open(filename)

In [5]:
tracksters = file["ticlNtuplizer/tracksters"]

In [6]:
tracksters.keys()

['event',
 'NClusters',
 'NTracksters',
 'time',
 'timeError',
 'regressed_energy',
 'raw_energy',
 'raw_em_energy',
 'raw_pt',
 'raw_em_pt',
 'barycenter_x',
 'barycenter_y',
 'barycenter_z',
 'trackster_barycenter_eta',
 'trackster_barycenter_phi',
 'EV1',
 'EV2',
 'EV3',
 'eVector0_x',
 'eVector0_y',
 'eVector0_z',
 'sigmaPCA1',
 'sigmaPCA2',
 'sigmaPCA3',
 'id_probabilities',
 'vertices_indexes',
 'vertices_x',
 'vertices_y',
 'vertices_z',
 'vertices_energy',
 'vertices_correctedEnergy',
 'vertices_correctedEnergyUncertainty',
 'vertices_multiplicity',
 'layer_cluster_seed']

In [7]:
vertices_indexes = tracksters['vertices_indexes'].array()

In [8]:
events = tracksters['event'].array()

In [9]:
energy = tracksters['raw_energy'].array()

In [10]:
vertices_x = tracksters['vertices_x'].array()
vertices_y = tracksters['vertices_y'].array()
vertices_z = tracksters['vertices_z'].array()

In [26]:
ver_x = ak.to_numpy(vertices_x[0,0])
ver_y = ak.to_numpy(vertices_y[0,0])
ver_z = ak.to_numpy(vertices_z[0,0])
diff_x = np.subtract.outer(ver_x,ver_x)
diff_y = np.subtract.outer(ver_y,ver_y)
diff_z = np.subtract.outer(ver_z,ver_z)

In [28]:
euclidean_matrix = np.sqrt(diff_x**2+diff_y**2+diff_z**2)

In [30]:
euclidean_matrix[:3,:3]

array([[0.        , 1.02107053, 3.08689687],
       [1.02107053, 0.        , 2.11901572],
       [3.08689687, 2.11901572, 0.        ]])

In [32]:
ver_E = ak.to_numpy(tracksters['vertices_energy'].array()[0,0])

In [33]:
ver_E

array([0.11006816, 0.38855466, 0.41010365, 1.13334072, 0.0397309 ,
       1.29394758, 0.99865955, 0.21616301, 0.11245865, 0.18585978,
       0.06195327, 0.04781175, 0.17037147, 0.44175372, 0.08615625,
       0.43010813, 0.06730957, 0.07404052, 0.03836645, 0.08817554,
       0.03165004, 0.18653318, 0.1070714 , 0.24781305, 0.16902466,
       0.11178791, 0.04309896])

In [44]:
max_val = np.max(euclidean_matrix[0][ver_E > ver_E[0]])

In [48]:
np.where(euclidean_matrix[0] == max_val)

25

In [42]:
euclidean_matrix[0] == min_val

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])