In [3]:
import numpy as np
import awkward as ak
import uproot

In [4]:
filename = "ntuples_13723003_0.root"
file = uproot.open(filename)

In [5]:
tracksters = file["ticlNtuplizer/tracksters"]

In [6]:
tracksters.keys()

['event',
 'NClusters',
 'NTracksters',
 'time',
 'timeError',
 'regressed_energy',
 'raw_energy',
 'raw_em_energy',
 'raw_pt',
 'raw_em_pt',
 'barycenter_x',
 'barycenter_y',
 'barycenter_z',
 'trackster_barycenter_eta',
 'trackster_barycenter_phi',
 'EV1',
 'EV2',
 'EV3',
 'eVector0_x',
 'eVector0_y',
 'eVector0_z',
 'sigmaPCA1',
 'sigmaPCA2',
 'sigmaPCA3',
 'id_probabilities',
 'vertices_indexes',
 'vertices_x',
 'vertices_y',
 'vertices_z',
 'vertices_energy',
 'vertices_correctedEnergy',
 'vertices_correctedEnergyUncertainty',
 'vertices_multiplicity',
 'layer_cluster_seed']

In [7]:
vertices_indexes = tracksters['vertices_indexes'].array()

In [8]:
events = tracksters['event'].array()

In [9]:
energy = tracksters['raw_energy'].array()

In [10]:
vertices_x = tracksters['vertices_x'].array()
vertices_y = tracksters['vertices_y'].array()
vertices_z = tracksters['vertices_z'].array()

In [26]:
ver_x = ak.to_numpy(vertices_x[0,0])
ver_y = ak.to_numpy(vertices_y[0,0])
ver_z = ak.to_numpy(vertices_z[0,0])
diff_x = np.subtract.outer(ver_x,ver_x)
diff_y = np.subtract.outer(ver_y,ver_y)
diff_z = np.subtract.outer(ver_z,ver_z)

In [28]:
euclidean_matrix = np.sqrt(diff_x**2+diff_y**2+diff_z**2)

In [30]:
euclidean_matrix[:3,:3]

array([[0.        , 1.02107053, 3.08689687],
       [1.02107053, 0.        , 2.11901572],
       [3.08689687, 2.11901572, 0.        ]])

In [32]:
ver_E = ak.to_numpy(tracksters['vertices_energy'].array()[0,0])

In [33]:
ver_E

array([0.11006816, 0.38855466, 0.41010365, 1.13334072, 0.0397309 ,
       1.29394758, 0.99865955, 0.21616301, 0.11245865, 0.18585978,
       0.06195327, 0.04781175, 0.17037147, 0.44175372, 0.08615625,
       0.43010813, 0.06730957, 0.07404052, 0.03836645, 0.08817554,
       0.03165004, 0.18653318, 0.1070714 , 0.24781305, 0.16902466,
       0.11178791, 0.04309896])

In [44]:
max_val = np.max(euclidean_matrix[0][ver_E > ver_E[0]])

In [50]:
np.where(euclidean_matrix[0] == max_val)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'

In [42]:
euclidean_matrix[0] == min_val

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [54]:
vertices_indexes00 = vertices_indexes[0,0]

In [57]:
for i in range(len(vertices_indexes00)):
    dist_array = euclidean_matrix[i][ver_E > ver_E[i]]
    if len(dist_array) == 0:
        continue
    min_val = np.min(dist_array)
    idx = np.where(euclidean_matrix[i] == min_val)[0][0]
    print("Node %d should be connected with node %d"%(vertices_indexes00[i],vertices_indexes00[idx]))

Node 1 should be connected with node 9
Node 9 should be connected with node 26
Node 26 should be connected with node 33
Node 33 should be connected with node 45
Node 43 should be connected with node 45
Node 59 should be connected with node 45
Node 63 should be connected with node 59
Node 72 should be connected with node 88
Node 88 should be connected with node 113
Node 98 should be connected with node 113
Node 109 should be connected with node 112
Node 112 should be connected with node 135
Node 113 should be connected with node 59
Node 134 should be connected with node 182
Node 135 should be connected with node 113
Node 136 should be connected with node 135
Node 159 should be connected with node 161
Node 160 should be connected with node 159
Node 161 should be connected with node 183
Node 181 should be connected with node 182
Node 182 should be connected with node 184
Node 183 should be connected with node 135
Node 184 should be connected with node 135
Node 204 should be connected with

In [65]:
from src.functions import euclideanMatrix

In [83]:
vertices_E = tracksters['vertices_energy'].array()
edges = ak.ArrayBuilder()
for ide, v_event in enumerate(vertices_indexes):
    edges.begin_list()
    for idt, v_trackster in enumerate(v_event):
        euMatr = euclideanMatrix(vertices_x[ide,idt],vertices_y[ide,idt],vertices_z[ide,idt])
        edges.begin_list()
        for idn, v_node in enumerate(v_trackster):
            dist_array = euMatr[idn][vertices_E[ide,idt] > vertices_E[ide,idt,idn]]
            if len(dist_array) == 0:
                continue
            min_val = np.min(dist_array)
            idx = np.where(euMatr[idn] == min_val)[0][0]
            edges.begin_tuple(2)
            edges.index(0).integer(v_node)
            edges.index(1).integer(v_trackster[idx])
            edges.end_tuple()
        edges.end_list()
    edges.end_list()

In [84]:
edges

<ArrayBuilder [[[(1, 9), (9, 26, ... ), (941, 873)]]] type='100 * var * var * (i...'>

In [86]:
edges[0,0]

<Array [(1, 9), (9, 26), ... 204), (261, 257)] type='26 * (int64, int64)'>